name: tds-car-park
services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: src/CarPark.Api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tds-car-park-network
    ports:
      - "7175:7175"
      - "5118:5118"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5118;https://+:7175"
      Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/aspnetapp.pfx"
      Kestrel__Certificates__Default__Password: "your_secure_dev_password"
    volumes:
      - ./certs/aspnetapp.pfx:/home/app/.aspnet/https/aspnetapp.pfx:z
  db:
    container_name: "db"
    image: postgres:latest
    environment:
      POSTGRES_DB: "carpark"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d carpark"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: null

networks:
  tds-car-park-network:
    driver: bridge